# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    name: build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php_version: ['7.4']

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up PHP ${{ matrix.php_version }}
        uses: shivammathur/setup-php@v2
        with:
          php-version: ${{ matrix.php_version }}

      - name: Install dependencies
        run: composer install --prefer-dist --no-progress
      - name: Run phpcs with Drupal coding standards.
        run: >
          ./vendor/bin/phpcs -p -s
      # - name: Set up PHP  Linter ${{ matrix.php_version }}
      #   uses: overtrue/phplint@8.0
      #   with:
      #     path: .
      #     options: --exclude=*.log,vendor
      # - name: Run phpcs with Drupal linter
      #   run: >
      #     ./vendor/bin/phplint 
      - name: Install Node for nightwatch testcase
        run: npm install && npm install protractor@latest --save-dev
      - name: Run the test case with the according to the test folder
        run: >
             ./node_modules/nightwatch/bin/nightwatch test
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out code
        uses: actions/checkout@v2